### PR TITLE
integrate CCP into Blockchain-Listener

### PR DESCRIPTION
**Pull request by robertschubert**
- introduced loglevels to save resources (log amount).
- integrated CCP into the listener: new field claimComplianceProviderResponses is read which contains Asset.claimComplianceProviderResponse from all assets of a given ContractDefinition in base64.

### CODE REVIEW

**Comment by robertschubert** [comment]
@uZhW8Rgl Thanks for a review. Unfortunately I cannot assign the PR to you.
Currently there is a problem when the listener triggers.
The log says:
```
Server listening on port 3005.
[INFO] Change on monitored contract detected! Please visit: https://better-call.dev/ghostnet/KT1QDheV2TkL3mitzYNKzunWYhSe6MmEPTh5/tokens
[INFO] 355
Webhook received: {
  hash: 'ooMyNsr8tDQHZUZgwzgSXWsXttH5E7RVnYQspzh4gZhfc3aM9Ja',
  kind: 'transaction',
  source: 'tz1Na21NimuuPXcQdHUk2en2XWYe9McyDDgZ',
  fee: '516',
  counter: '11783312',
  gas_limit: '982',
  storage_limit: '232',
  amount: '0',
  destination: 'KT1QDheV2TkL3mitzYNKzunWYhSe6MmEPTh5',
  parameters: { entrypoint: 'mint', value: [ [Object] ] },
  metadata: {
    balance_updates: [ [Object], [Object] ],
    operation_result: {
      status: 'applied',
      storage: [Array],
      balance_updates: [Array],
      consumed_milligas: '881852',
      storage_size: '83942',
      paid_storage_size_diff: '232',
      lazy_storage_diff: [Array]
    }
  }
}
[INFO] Status:
[INFO] Body: 
[INFO] No metadata found
[INFO] Execution time: 0.067 seconds
[INFO] 1 tokens were returned
[INFO] No metadata found
```
I will have a look. But why dont we see Status and Body? I would expect something like 200? 
Also I guess I need a deeper understanding in the interface between the EDC-Blockchain-Catalog and this listener component. Do you think we can have a call?

**Comment by uZhW8Rgl** [comment]
Hi @robertschubert,

it takes some time to write the information and confirm it on the blockchain. The listener is triggered immediately that the mint function has been triggered but there is a delay until the metadata is also readable. The delay depends on the workload of the blockchain and can take from 2 minutes up to hours. That is why there is a loop checking every minute and repeating the reading attempt. Unfortunately after 3 p.m. the testnet takes longer to append changes.

**Review by uZhW8Rgl — CHANGES_REQUESTED** [review]
I changed the recursive limit to 30 and got an positive result after 7 minutes: 
[INFO] Status:
[INFO] Body:
[INFO] No metadata found
[INFO] Execution time: 0.24 seconds
[INFO] 1 tokens were returned
[INFO] No metadata found
[INFO] No metadata found
[INFO] No metadata found
[INFO] No metadata found
[INFO] No metadata found
[INFO] No metadata found
[INFO] No metadata found
[INFO] Metadata for "verifiablePresentation" found
[INFO] Status of FC response:
But it looks like the thread dies here, after finding the metadata.

**Comment by robertschubert** [comment]
Hi @uZhW8Rgl 
Thanks for looking into it.

Here my thoughts:
- The fact that the thread dies after processing the metadata is good and I would also expect this. After the event is received it spawns a thread (with async) which then calls the recursion. The thread should not live after metadata was processed.
- I am wondering why we do not see a value in the log lines. I would expect a 200 for Status 

```
[INFO] Status:
[INFO] Body:
[INFO] Status of FC response:
```

  Do you have an idea?
- My next change will be to add the thread-id and timestamp to the logs.
- I will also increase the number of recursions.
- I was not aware that it can take hours to be able to process the meta data. I guess we need to find another solution and we should not use the blockchain as middleware for propagation into the catalogue. Let's discuss this in our next meeting on Thursday. Can you speak with Maria and Julian upfront?
- spawning a new thread on every event and then having multiple threads sleeping / waiting for metadata will not scale. For now / demonstration purposes it would work out, but if there are huge workloads the application would just explode because of many open threads and no limitation for creating new threads (something like a thread pool or message queue).

**Comment by uZhW8Rgl** [comment]
The messages are missing because your new "Console" method expects a "+" to append an value to the String...
So for example: console.log('Status of FC response: ', response.status); -> Console.info('Status of FC response: ' + response.status);

The delay is a testnet issue, this will not be of much concern on the paid mainnet, Maria is well aware of the delay. I am not in the office next week, but can message Maria and Julian.

**Comment by robertschubert** [comment]
> The messages are missing because your new "Console" method expects a "+" to append an value to the String... So for example: console.log('Status of FC response: ', response.status); -> Console.info('Status of FC response: ' + response.status);
> 
> The delay is a testnet issue, this will not be of much concern on the paid mainnet, Maria is well aware of the delay. I am not in the office next week, but can message Maria and Julian.

Thanks :) Will change this, too. Overseen it, js is not my world ;)
Have a good time!

**Comment by robertschubert** [comment]
@uZhW8Rgl  I added a commit. 
Once I have tested it in my environment I will give you a hint for another review.

**Review by uZhW8Rgl — APPROVED** [review]
Thanks. Looks all good and runs on my setup. ;)

**Pull request merged**
